version: "3"
services:
        ping_no_gw:
                restart: unless-stopped
                build: .
                environment:
                        - IP_1=8.8.8.8
                        - NAME_1=google
                        - GROUP_1=Reference
                          #Gateway
                        - GATEWAY=192.168.4.1
                ports:
                        - 8081:8080
                cap_add:
                        - NET_ADMIN
        ping_gw:
                restart: unless-stopped
                build: .
                environment:
                       - IP_1=8.8.8.8
                       - NAME_1=Google
                       - GROUP_1=Reference
                ports:
                        - 8082:8080

